@startuml
hide empty members
set namespaceSeparator none

class "/dialogs" {
}

class "GET /dialogs" {
.. query ..
{field} integer limit
.. responses ..
200: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



class "POST /dialogs" {

.. responses ..
201: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



"/dialogs" ..> "GET /dialogs"
"/dialogs" ..> "POST /dialogs"



class "/dialogs/{dialogId}" {
}

class "GET /dialogs/{dialogId}" {
.. path ..
{field} string <b>dialogId</b>
.. responses ..
200: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



"/dialogs/{dialogId}" ..> "GET /dialogs/{dialogId}"



class "/dialogs/{dialogId}/messages" {
}

class "GET /dialogs/{dialogId}/messages" {
.. path ..
{field} string <b>dialogId</b>
.. query ..
{field} integer limit
.. responses ..
200: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



class "POST /dialogs/{dialogId}/messages" {
.. header ..
{field} string <b>content</b>
{field} string <b>senderID</b>
{field} string <b>recipientID</b>
.. path ..
{field} string <b>dialogId</b>
.. responses ..
201: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



"/dialogs/{dialogId}/messages" ..> "GET /dialogs/{dialogId}/messages"
"/dialogs/{dialogId}/messages" ..> "POST /dialogs/{dialogId}/messages"



class "/dialogs/{dialogId}/crisises" {
}

class "POST /dialogs/{dialogId}/crisises" {
.. header ..
{field} string <b>reason</b>
{field} string <b>starterID</b>
{field} string <b>recipientID</b>
.. path ..
{field} string <b>dialogId</b>
.. responses ..
201: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



"/dialogs/{dialogId}/crisises" ..> "POST /dialogs/{dialogId}/crisises"



class "/dialogs/{dialogId}/crisises/{crisisId}" {
}

class "POST /dialogs/{dialogId}/crisises/{crisisId}" {
.. header ..
{field} string <b>reason</b>
{field} string <b>starterID</b>
{field} string <b>recipientID</b>
.. path ..
{field} string <b>dialogId</b>
{field} string <b>crisisId</b>
.. responses ..
201: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



"/dialogs/{dialogId}/crisises/{crisisId}" ..> "POST /dialogs/{dialogId}/crisises/{crisisId}"



class "/statements/{statementId}/requests" {
}

class "POST /statements/{statementId}/requests" {
.. header ..
{field} string <b>invitation</b>
{field} string <b>senderID</b>
.. path ..
{field} string <b>statementId</b>
.. responses ..
201: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



"/statements/{statementId}/requests" ..> "POST /statements/{statementId}/requests"



class "/statements/{statementId}/requestes/{requestId}" {
}

class "POST /statements/{statementId}/requestes/{requestId}" {
.. header ..
{field} string <b>reason</b>
{field} string <b>starterID</b>
{field} string <b>recipientID</b>
.. path ..
{field} string <b>statementId</b>
{field} string <b>requestId</b>
.. responses ..
201: {field} <i>not specified</i> 
default: {field} <i>not specified</i> 
}



"/statements/{statementId}/requestes/{requestId}" ..> "POST /statements/{statementId}/requestes/{requestId}"



class "/sign-up/" {
}

class "POST /sign-up/" {

.. responses ..
200: {field} <i>not specified</i> 
400: {field} <i>not specified</i> 
401: {field} <i>not specified</i> 
}



"/sign-up/" ..> "POST /sign-up/"



@enduml
